x-template: &template
    build:
        context: ..
        dockerfile: .devcontainer/Dockerfile
    network_mode: host
    shm_size: "8gb"
    volumes:
        - ..:/workspace:cached
        - ../resources:/resources:cached
        - $HOME/.ssh/:/home/ubuntu/.ssh
        - /var/run/docker.sock:/var/run/docker.sock
        - mlflow-data:/workspace/mlruns
    command: /bin/sh -c "while true; do :; done"
    env_file:
        - ../.devcontainer/.env

services:
    devcontainer-gpu:
        <<: *template
        container_name: {{cookiecutter.repo_name}}-devcontainer-cpu
        deploy:
            resources:
                reservations:
                devices:
                    - capabilities: [ gpu ]

    devcontainer:
        <<: *template
        container_name: {{cookiecutter.repo_name}}-devcontainer-gpu

volumes:
    mlflow-data:
        name: mlflow-data
